### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by tbaddade** [yakamara/gulp-tasks#3]
```
warning @yakamara/gulp-tasks > modernizr > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @yakamara/gulp-tasks > gulp-sass > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @yakamara/gulp-tasks > gulp-sass > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by gharlan** [comment]
In modernizr ist es gelöst, müssen nur auf ein neues Release warten: https://github.com/Modernizr/Modernizr/issues/2524
Wobei wir dann hier im repo nichts machen müssen, sondern es reicht dann in den Projekten zu aktualisieren.
Hier im Repo müssen wir immer nur updaten, wenn es neue Major-Versionen gibt.

Für node-sass gibt es noch keine Lösung: https://github.com/sass/node-sass/issues/2851

**Comment by gharlan** [comment]
Äh bzw bei modernizr wird auch mit dem neuen Release die Warnung nicht verschwinden, da die erst mal bei der legacy version von mkdirp bleiben.

Ich schließe hier, da es nicht in unserer Macht ist.

**Comment by tbaddade** [comment]
> da es nicht in unserer Macht ist.

Und ich dachte die Macht sei mit dir.
